### ISSUE TITLE
I follow your guide, but it doesn't work.

### ISSUE THREAD

**Issue by adamshen** [AnyISalIn/some_config_file#1]
/Users/shenqing/.tmux.conf:59: usage: bind-key [-cnr] [-T key-table] key command [arguments]                                                                                    [0/0]
/Users/shenqing/.tmux.conf:60: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/Users/shenqing/.tmux.conf:63: usage: unbind-key [-an] [-T key-table] key
/Users/shenqing/.tmux.conf:64: usage: bind-key [-cnr] [-T key-table] key command [arguments]

**Comment by AnyISalIn** [comment]
应该是 tmux 版本的问题，你用 `tmux -V` 查看一下你当前的版本

**Comment by adamshen** [comment]
my tmux version is 2.6

**Comment by adamshen** [comment]
use https://github.com/tony/tmux-config
AnyISalIn is creating value. I won't bother you again.
